language: php

sudo: false

services:
    - mysql

php:
    - '7.0'

env:
    global:
        - APP_DEBUG=false DB_DATABASE=hustoj DB_USERNAME=root

before_script:
  - "mysql -e 'create database `hustoj`;'"
  - composer install
  - cp .env.example .env
  - php artisan key:generate
  - php artisan migrate

script:
    - phpunit --coverage-text