language: php

sudo: false

services:
    - mysql

php:
    - '7.0'

env:
    global:
        - APP_DEBUG=false DB_DATABASE=travis DB_USERNAME=travis

script:
    - composer install
    - cp .env.production .env
    - php artisan key:generate
    - phpunit --coverage-text