language: php

sudo: false

services:
    - mysql

php:
    - '7.4'

env:
    global:
        - APP_DEBUG=false

before_script:
    - composer install --no-interaction
    - cp .env.travis .env
    - php artisan key:generate
    - php artisan migrate

cache:
  directories:
    - node_modules
    - vendor

before_install:
    - mysql -e 'create database `hustoj`;'

script:
    - phpunit --coverage-text
